# Generated by Django 4.1.7 on 2024-10-24 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import masters.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('brand_code', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('short_code', models.CharField(max_length=30)),
                ('short_description', models.TextField(max_length=100)),
                ('long_description', models.TextField(max_length=100)),
                ('keyword', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shortname', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('currency_name', models.CharField(max_length=10)),
                ('currency_code', models.CharField(max_length=4)),
                ('mob_code', models.CharField(max_length=5)),
                ('mob_no_len', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('manufacturer_code', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'manufracturer',
            },
        ),
        migrations.CreateModel(
            name='PurchaseAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('purchase_account_code', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'purchase_account',
            },
        ),
        migrations.CreateModel(
            name='SalesAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sales_account_code', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'sales_account',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('unit_code', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'unit',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='OfferSlide',
            fields=[
                ('offer_slider_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('offer_slider_content', models.TextField(max_length=100, null=True)),
                ('offer_slider_status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerslide_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerslide_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offerslide',
            },
        ),
        migrations.CreateModel(
            name='GridItem',
            fields=[
                ('grid_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grid_item_name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to=masters.models.upload_to_grid)),
                ('grid_content', models.TextField()),
                ('grid_title', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grid_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grid_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'griditem',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=50, unique=True)),
                ('district_code', models.CharField(max_length=10, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='district_by_user', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.state')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=70)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_by_user', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.state')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('banner_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('banner_name', models.CharField(max_length=30)),
                ('banner_status', models.BooleanField(default=True)),
                ('banner_description', models.CharField(max_length=100)),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to=masters.models.upload_to_gal)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banner_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'banner',
            },
        ),
    ]
