# Generated by Django 4.1.7 on 2024-10-24 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('1', 'Goods'), ('2', 'Service')], default=1, max_length=20)),
                ('sku', models.CharField(blank=True, max_length=30, null=True)),
                ('returnable_item', models.BooleanField(default=True)),
                ('dimensions', models.CharField(blank=True, max_length=30, null=True)),
                ('dimension_type', models.CharField(choices=[('1', 'cm'), ('2', 'in')], default=1, max_length=20)),
                ('weight', models.CharField(blank=True, max_length=30, null=True)),
                ('weight_type', models.CharField(choices=[('1', 'kg'), ('2', 'g'), ('2', 'lb'), ('2', 'oz')], default=1, max_length=20)),
                ('mpn', models.CharField(blank=True, max_length=30, null=True)),
                ('upc', models.CharField(blank=True, max_length=30, null=True)),
                ('isbn', models.CharField(blank=True, max_length=30, null=True)),
                ('ean', models.CharField(blank=True, max_length=30, null=True)),
                ('selling_price', models.CharField(blank=True, max_length=30, null=True)),
                ('cost_price', models.CharField(blank=True, max_length=30, null=True)),
                ('account', models.CharField(blank=True, max_length=30, null=True)),
                ('rating', models.CharField(max_length=30)),
                ('xs', models.BooleanField(default=False)),
                ('sm', models.BooleanField(default=False)),
                ('md', models.BooleanField(default=False)),
                ('lg', models.BooleanField(default=False)),
                ('xl', models.BooleanField(default=False)),
                ('xxl', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=70, null=True)),
                ('opening_stock', models.CharField(blank=True, max_length=30, null=True)),
                ('opening_stock_per_unit', models.CharField(blank=True, max_length=30, null=True)),
                ('reorder_point', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=inventory.models.upload_to_gal)),
                ('product_description', models.TextField(max_length=1000)),
                ('box_description', models.TextField(max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.category')),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otp',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wishlist_added_by', to=settings.AUTH_USER_MODEL)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
        migrations.CreateModel(
            name='ItemImages',
            fields=[
                ('id_image', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to=inventory.models.upload_to_gal_item)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id_images', to='inventory.item')),
            ],
            options={
                'db_table': 'item_images',
            },
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=20, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bag_added_by', to=settings.AUTH_USER_MODEL)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
            ],
            options={
                'db_table': 'bag',
            },
        ),
    ]
