# Generated by Django 4.1.7 on 2024-10-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='lg',
        ),
        migrations.RemoveField(
            model_name='item',
            name='md',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sm',
        ),
        migrations.RemoveField(
            model_name='item',
            name='xl',
        ),
        migrations.RemoveField(
            model_name='item',
            name='xs',
        ),
        migrations.RemoveField(
            model_name='item',
            name='xxl',
        ),
    ]
