# Generated by Django 4.1.7 on 2024-10-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_item_lg_remove_item_md_remove_item_sm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
